"use client"

import { useState } from "react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertCircle, TrendingDown, TrendingUp, Target, Info, Shield, BarChart3, Clock, CheckCircle2, Code } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Label } from "@/components/ui/label"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { dtoViolationReports } from "@/lib/data"

// Import proper components
import { DtoModuleLeaderboard } from "@/components/dto-module-leaderboard"
import { DtoViolationHeatmap } from "@/components/dto-violation-heatmap"
import { DtoTimelineChart } from "@/components/dto-timeline-chart"
import { DtoOverviewChart } from "@/components/dto-overview-chart"
import { DtoViolationsExplorer } from "@/components/dto-violations-explorer"

export function DtoUsageDashboard() {
  const hasData = dtoViolationReports && dtoViolationReports.length > 0

  // Default: current = latest commit, compare = first (earliest) commit
  const [selectedReportIndex, setSelectedReportIndex] = useState(
    hasData ? dtoViolationReports.length - 1 : 0
  )
  const [compareReportIndex, setCompareReportIndex] = useState(0)

  const formatDate = (date: Date) => {
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  }

  // No data state
  if (!hasData) {
    return (
      <main className="flex-1 px-4 py-6 sm:px-6 lg:px-8">
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-slate-900">DTO Usage Migration</h2>
          <p className="text-sm text-slate-500">Track entity-to-DTO migration progress across server modules</p>
        </div>

        <Alert>
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Awaiting First Report</AlertTitle>
          <AlertDescription>
            DTO violation reports will be generated by the CI pipeline.
            Once the first report is generated, you'll see migration progress data here.
            <ul className="list-disc list-inside mt-3 space-y-1 text-sm">
              <li><strong>Entity Return Violations:</strong> REST controllers returning @Entity types</li>
              <li><strong>Entity Input Violations:</strong> REST controllers accepting @Entity in @RequestBody</li>
              <li><strong>DTO Entity Field Violations:</strong> DTOs containing @Entity field references</li>
            </ul>
          </AlertDescription>
        </Alert>
      </main>
    )
  }

  const currentReport = dtoViolationReports[selectedReportIndex]
  const compareReport = dtoViolationReports[compareReportIndex]

  const current = currentReport.dtoViolations.totals
  const compare = compareReport.dtoViolations.totals

  const totalCurrent = current.entityReturnViolations + current.entityInputViolations + current.dtoEntityFieldViolations
  const totalCompare = compare.entityReturnViolations + compare.entityInputViolations + compare.dtoEntityFieldViolations
  const totalChange = totalCurrent - totalCompare
  const violationsFixed = totalCompare - totalCurrent

  // Calculate compliant modules
  const compliantModules = Object.values(currentReport.dtoViolations.modules).filter(
    m => m.entityReturnViolations === 0 && m.entityInputViolations === 0 && m.dtoEntityFieldViolations === 0
  ).length
  const totalModules = Object.keys(currentReport.dtoViolations.modules).length

  return (
    <main className="flex-1 px-4 py-6 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-bold text-slate-900">DTO Usage Migration</h2>
              <Badge
                variant={violationsFixed > 0 ? "default" : violationsFixed < 0 ? "destructive" : "secondary"}
                className="ml-2"
              >
                {violationsFixed > 0 ? <TrendingDown className="h-3 w-3 mr-1" /> :
                 violationsFixed < 0 ? <TrendingUp className="h-3 w-3 mr-1" /> : null}
                {violationsFixed > 0 ? `${violationsFixed} fixed` :
                 violationsFixed < 0 ? `${Math.abs(violationsFixed)} added` : 'No change'}
              </Badge>
            </div>
            <p className="text-sm text-slate-500">
              Commit: {currentReport.metadata.artemis.commitHash.substring(0, 8)} - {formatDate(currentReport.metadata.artemis.commitDate)}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Label htmlFor="compare-version">Compare with:</Label>
              <Select
                value={compareReportIndex.toString()}
                onValueChange={(val) => setCompareReportIndex(parseInt(val))}
              >
                <SelectTrigger id="compare-version" className="w-[240px]">
                  <SelectValue placeholder="Select version to compare" />
                </SelectTrigger>
                <SelectContent>
                  {dtoViolationReports.map((report, index) => (
                    <SelectItem key={index} value={index.toString()}>
                      {formatDate(report.metadata.artemis.commitDate)} - {report.metadata.artemis.commitHash.substring(0, 7)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-center gap-2">
              <Label htmlFor="current-version">Current:</Label>
              <Select
                value={selectedReportIndex.toString()}
                onValueChange={(val) => setSelectedReportIndex(parseInt(val))}
              >
                <SelectTrigger id="current-version" className="w-[240px]">
                  <SelectValue placeholder="Select current version" />
                </SelectTrigger>
                <SelectContent>
                  {dtoViolationReports.map((report, index) => (
                    <SelectItem key={index} value={index.toString()}>
                      {formatDate(report.metadata.artemis.commitDate)} - {report.metadata.artemis.commitHash.substring(0, 7)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
      </div>

      {/* Progress Cards */}
      <div className="grid grid-cols-1 gap-6 md:grid-cols-4 mb-6">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-slate-500 flex items-center gap-2">
              <Target className="h-4 w-4" />
              Total Violations
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-slate-900">{totalCurrent}</span>
              {totalChange !== 0 && (
                <Badge variant={totalChange < 0 ? "default" : "destructive"}>
                  {totalChange < 0 ? totalChange : `+${totalChange}`}
                </Badge>
              )}
            </div>
            <p className="text-xs text-slate-500 mt-1">Goal: 0 violations</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-slate-500 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4" />
              Compliant Modules
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-bold text-slate-900">{compliantModules}</span>
              <span className="text-lg text-slate-500">/ {totalModules}</span>
            </div>
            <p className="text-xs text-slate-500 mt-1">Modules with 0 violations</p>
            <Progress value={(compliantModules / totalModules) * 100} className="mt-2 h-2" />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-slate-500 flex items-center gap-2">
              <BarChart3 className="h-4 w-4" />
              Violations Fixed
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-baseline gap-2">
              <span className={`text-3xl font-bold ${violationsFixed > 0 ? 'text-green-600' : violationsFixed < 0 ? 'text-red-600' : 'text-slate-500'}`}>
                {violationsFixed > 0 ? `+${violationsFixed}` : violationsFixed}
              </span>
            </div>
            <p className="text-xs text-slate-500 mt-1">Since comparison report</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-slate-500 flex items-center gap-2">
              <Clock className="h-4 w-4" />
              Breakdown
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-1 text-sm">
              <div className="flex justify-between">
                <span className="text-slate-600">Returns</span>
                <span className="font-medium">{current.entityReturnViolations}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Inputs</span>
                <span className="font-medium">{current.entityInputViolations}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Fields</span>
                <span className="font-medium">{current.dtoEntityFieldViolations}</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="leaderboard">
        <TabsList className="grid w-full grid-cols-5 mb-6">
          <TabsTrigger value="leaderboard">Module Compliance</TabsTrigger>
          <TabsTrigger value="timeline">Timeline</TabsTrigger>
          <TabsTrigger value="heatmap">Heatmap</TabsTrigger>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="data">Violations Explorer</TabsTrigger>
        </TabsList>

        <TabsContent value="leaderboard" className="mt-0">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="md:col-span-2">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Shield className="h-5 w-5 text-green-500" />
                    <div>
                      <CardTitle>Module DTO Compliance</CardTitle>
                      <CardDescription>Ranked by violations fixed - lower total is better</CardDescription>
                    </div>
                  </div>
                  <TooltipProvider>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <Button variant="ghost" size="icon">
                          <Info className="h-4 w-4" />
                        </Button>
                      </TooltipTrigger>
                      <TooltipContent>
                        <p className="max-w-xs">
                          Modules are ranked by the number of violations they have fixed since the comparison date.
                          Green rows indicate fully compliant modules (0 violations).
                          Trophy/medals go to modules that fixed the most violations.
                        </p>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </div>
              </CardHeader>
              <CardContent>
                <DtoModuleLeaderboard currentReport={currentReport} compareReport={compareReport} />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <div className="flex items-center gap-2">
                  <BarChart3 className="h-5 w-5 text-purple-500" />
                  <div>
                    <CardTitle>Violation Breakdown</CardTitle>
                    <CardDescription>Current violations by type</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <DtoOverviewChart currentReport={currentReport} compareReport={compareReport} />
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="heatmap" className="mt-0">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Target className="h-5 w-5 text-orange-500" />
                  <div>
                    <CardTitle>Violation Focus Areas</CardTitle>
                    <CardDescription>Identify which modules and violation types need attention</CardDescription>
                  </div>
                </div>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button variant="ghost" size="icon">
                        <Info className="h-4 w-4" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p className="max-w-xs">
                        This heatmap shows violation counts by module and type.
                        Green (0) is fully compliant. Red/dark red indicates high violation counts.
                        Focus on the darkest cells first.
                      </p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>
            </CardHeader>
            <CardContent>
              <DtoViolationHeatmap currentReport={currentReport} compareReport={compareReport} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="timeline" className="mt-0">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Clock className="h-5 w-5 text-blue-500" />
                  <div>
                    <CardTitle>Migration Progress Timeline</CardTitle>
                    <CardDescription>Track violation reduction over time</CardDescription>
                  </div>
                </div>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button variant="ghost" size="icon">
                        <Info className="h-4 w-4" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p className="max-w-xs">
                        This chart shows how violations are trending over time.
                        The red area represents total violations (should decrease).
                        The green line shows the percentage of fully compliant modules.
                      </p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>
            </CardHeader>
            <CardContent>
              <DtoTimelineChart data={dtoViolationReports} currentIndex={selectedReportIndex} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="overview" className="mt-0">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <div className="flex items-center gap-2">
                  <Info className="h-5 w-5 text-slate-500" />
                  <div>
                    <CardTitle>What These Violations Mean</CardTitle>
                    <CardDescription>Understanding the three violation types and how to fix them</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="p-4 bg-red-50 rounded-lg border border-red-100">
                    <h4 className="font-medium text-red-900">Entity Return Violations</h4>
                    <p className="text-3xl font-bold text-red-700 my-2">{current.entityReturnViolations}</p>
                    <p className="text-sm text-red-700">
                      REST controllers returning @Entity types directly.
                    </p>
                    <p className="text-xs text-red-600 mt-2 font-medium">
                      Fix: Create DTOs and use mappers/projections.
                    </p>
                  </div>
                  <div className="p-4 bg-orange-50 rounded-lg border border-orange-100">
                    <h4 className="font-medium text-orange-900">Entity Input Violations</h4>
                    <p className="text-3xl font-bold text-orange-700 my-2">{current.entityInputViolations}</p>
                    <p className="text-sm text-orange-700">
                      @RequestBody accepting @Entity types.
                    </p>
                    <p className="text-xs text-orange-600 mt-2 font-medium">
                      Fix: Create request DTOs with only needed fields.
                    </p>
                  </div>
                  <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-100">
                    <h4 className="font-medium text-yellow-900">DTO Field Violations</h4>
                    <p className="text-3xl font-bold text-yellow-700 my-2">{current.dtoEntityFieldViolations}</p>
                    <p className="text-sm text-yellow-700">
                      DTOs containing @Entity field references.
                    </p>
                    <p className="text-xs text-yellow-600 mt-2 font-medium">
                      Fix: DTOs should only have primitives, enums, or nested DTOs.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Alert>
              <CheckCircle2 className="h-4 w-4" />
              <AlertTitle>Full Coverage Data</AlertTitle>
              <AlertDescription>
                <p className="text-sm">
                  All violations detected via static source code analysis using JavaParser.
                  Data includes detailed file paths, line numbers, and endpoint information.
                </p>
              </AlertDescription>
            </Alert>
          </div>
        </TabsContent>

        <TabsContent value="data" className="mt-0">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Code className="h-5 w-5 text-slate-500" />
                <div>
                  <CardTitle>All Violations Explorer</CardTitle>
                  <CardDescription>
                    Search and filter all {currentReport.dtoViolations.totals.entityReturnViolations + currentReport.dtoViolations.totals.entityInputViolations + currentReport.dtoViolations.totals.dtoEntityFieldViolations} violations - click Source to view in GitHub
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <DtoViolationsExplorer data={currentReport} />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </main>
  )
}
